version: '3.8'

services:
  mysql-usuarios:
    image: mysql:8.0
    container_name: mysql-usuarios
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ronald1234
      MYSQL_DATABASE: usuario_db
      MYSQL_USER: user_app
      MYSQL_PASSWORD: pass_app
    ports:
      - "3309:3306"
    volumes:
      - mysql_usuarios_data:/var/lib/mysql
      - ./Usuario-ControlUsuarios/auth_service/script/auth_service.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chapinflix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  mysql-catalogo:
    image: mysql:8.0
    container_name: mysql-catalogo
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass1
      MYSQL_DATABASE: SA_PROJECT
      MYSQL_USER: user_sa
      MYSQL_PASSWORD: pass1
    ports:
      - "3308:3306"
    volumes:
      - mysql_catalogo_data:/var/lib/mysql
      - ./backend/servicio_catalogo/script/script.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chapinflix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql-interaccion:
    image: mysql:8.0
    container_name: mysql-interaccion
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: DB_interaccion
      MYSQL_USER: chapinflix
      MYSQL_PASSWORD: chapinflix123
    ports:
      - "3307:3306"
    volumes:
      - mysql_interaccion_data:/var/lib/mysql
      - ./microservicio-interaccion/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chapinflix-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  ms-usuarios:
    build:
      context: ./Usuario-ControlUsuarios/auth_service
      dockerfile: Dockerfile
    container_name: ms-usuarios
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      # Configuración de base de datos
      DB_NOMBRE: usuario_db
      DB_USUARIO: user_app
      DB_CONTRASENA: pass_app
      DB_HOST: mysql-usuarios
      DB_PORT: 3306
      # Configuración JWT
      JWT_SECRETO: software-avanzado-secret-key-prayecto1
      JWT_EXPIRACION: 1h
      # Configuración de correo
      CORREO_USUARIO: ronald.inge2013@gmail.com
      CORREO_CONTRASENA: "umyo zflq rlea hjip"
    depends_on:
      mysql-usuarios:
        condition: service_healthy
    networks:
      - chapinflix-network
    volumes:
      - ./Usuario-ControlUsuarios/auth_service:/app
      - /app/node_modules

  ms-catalogo:
    build:
      context: ./backend/servicio_catalogo
      dockerfile: Dockerfile
    container_name: ms-catalogo
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      SERVICE_NAME: catalog-service
      # Configuración de base de datos
      DB_HOST: mysql-catalogo
      DB_PORT: 3306
      DB_DATABASE: SA_PROJECT
      DB_USER: user_sa
      DB_PASSWORD: pass1
      # Logging
      LOG_LEVEL: debug
      LOG_FILE: logs/catalog-service.log
    depends_on:
      mysql-catalogo:
        condition: service_healthy
    networks:
      - chapinflix-network
    volumes:
      - ./backend/servicio_catalogo:/app
      - /app/node_modules
      - ./backend/servicio_catalogo/uploads:/app/uploads

  ms-interaccion:
    build:
      context: ./microservicio-interaccion
      dockerfile: Dockerfile
    container_name: ms-interaccion
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      PORT: 3002
      HOST: 0.0.0.0
      # Configuración de base de datos
      DB_HOST: mysql-interaccion
      DB_PORT: 3306
      DB_USER: chapinflix
      DB_PASSWORD: chapinflix123
      DB_NAME: DB_interaccion
      DB_CONNECTION_LIMIT: 10
      DB_QUEUE_LIMIT: 0
      # Configuración CORS
      CORS_ORIGIN: "*"
      # Rate limiting
      RATE_LIMIT_WINDOW: 15
      RATE_LIMIT_MAX: 100
      # Logs
      LOG_LEVEL: debug
      LOG_FILE: logs/app.log
      # Service info
      SERVICE_NAME: ms-interaccion
      SERVICE_VERSION: 1.0.0
    depends_on:
      mysql-interaccion:
        condition: service_healthy
    networks:
      - chapinflix-network
    volumes:
      - ./microservicio-interaccion/src:/app/src
      - /app/node_modules

  nginx-gateway:
    image: nginx:alpine
    container_name: nginx-gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - ms-usuarios
      - ms-catalogo
      - ms-interaccion
    networks:
      - chapinflix-network

networks:
  chapinflix-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16

volumes:
  mysql_usuarios_data:
    driver: local
  mysql_catalogo_data:
    driver: local
  mysql_interaccion_data:
    driver: local